version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: openjdk:17-alpine
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: simple_bookshelf
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
