version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: openjdk:17-alpine
    ports:
      - 8080:8080
    command:
      - -jar
      - build/libs/simple-bookshelf-0.0.1-SNAPSHOT.jar
      - --spring.profiles.active=docker
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: simple_bookshelf
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD
